albania = ['greece', 'north-macedonia', 'montenegro']
australia = ['united-kingdom', 'ireland']
austria = ['czech-republic', 'hungary', 'italy', 'switzerland', 'germany', 'slovenia']
azerbaijan = ['armenia', 'georgia']
belgium = ['the-netherlands', 'germany', 'luxembourg', 'france']
bulgaria = ['romania', 'greece', 'north-macedonia', 'serbia', 'romania']
croatia = ['hungary', 'serbia', 'slovenia']
cyprus = ['greece', 'israel', 'malta']
czech-republic = ['austria', 'poland', 'germany']
denmark = ['germany', 'sweden', 'norway']
estonia = ['finland', 'russia', 'latvia']
finland = ['norway', 'russia', 'estonia', 'sweden']
france = ['belgium', 'luxembourg', 'germany', 'monaco', 'switzerland', 'italy', 'spain']
georgia = ['armenia', 'russia', 'azerbaijan']
germany = ['austria', 'belgium', 'czech-republic', 'denmark', 'france', 'poland', 'switzerland', 'luxembourg', 'the-netherlands']
greece = ['albania', 'bulgaria', 'cyprus', 'north-macedonia']
hungary = ['austria', 'croatia', 'ukraine', 'romania', 'serbia', 'slovenia']
iceland = ['norway', 'ireland', 'united-kingdom']
ireland = ['australia', 'united-kingdom', 'iceland']
israel = ['cyprus']
italy = ['austria', 'france', 'malta', 'san-marino', 'slovenia', 'switzerland']
latvia = ['russia', 'lithuania']
lithuania = ['latvia', 'poland']
luxembourg = ['belgium', 'france', 'germany']
malta = ['cyprus', 'italy']
moldova = ['ukraine', 'romania']
monaco = ['france']
montenegro = ['albania', 'serbia']
the-netherlands = ['belgium', 'germany']
north-macedonia = ['albania', 'bulgaria', 'greece', 'serbia']
norway = ['denmark', 'finland', 'iceland', 'sweden', 'russia']
poland = ['czech-republic', 'germany', 'lithuania', 'russia', 'ukraine']
portugal = ['spain']
romania = ['bulgaria', 'hungary', 'moldova', 'ukraine', 'serbia']
russia = ['estonia', 'finland', 'georgia', 'latvia', 'norway', 'poland', 'ukraine']
san-marino = ['italy']
serbia = ['bulgaria', 'croatia', 'hungary', 'montenegro', 'north-macedonia', 'romania']
slovenia = ['austria', 'croatia', 'hungary', 'italy']
spain = ['france', 'portugal']
sweden = ['denmark', 'finland', 'norway']
switzerland = ['austria', 'france', 'germany', 'italy']
ukraine = ['hungary', 'moldova', 'poland', 'romania', 'russia']
united-kingdom = ['australia', 'iceland', 'ireland']
