# Generated by Django 3.1.7 on 2021-05-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceincident',
            name='predicted',
            field=models.BooleanField(default=False),
        ),
    ]
