# Generated by Django 3.1.7 on 2021-05-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('english', models.CharField(max_length=128)),
                ('hashtag', models.CharField(max_length=3)),
                ('languages', models.ManyToManyField(blank=True, to='contests.Language')),
                ('neighbours', models.ManyToManyField(blank=True, related_name='_country_neighbours_+', to='contests.Country')),
            ],
            options={
                'ordering': ['english'],
            },
        ),
    ]
