# Generated by Django 3.1.7 on 2021-05-24 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.country')),
            ],
        ),
    ]
