# Generated by Django 3.1.7 on 2021-05-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_singer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('singer', models.ManyToManyField(to='contests.Singer')),
            ],
        ),
    ]
