# Generated by Django 3.1.7 on 2021-05-24 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.artist')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.country')),
                ('languages', models.ManyToManyField(blank=True, to='contests.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.country')),
            ],
            options={
                'unique_together': {('country', 'contest')},
            },
        ),
    ]
