# Generated by Django 3.1.7 on 2021-05-24 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_participant_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('final', 'Grand Final'), ('first-semi', 'First Semi-Final'), ('second-semi', 'Second Semi-Final')], max_length=16)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.show')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.song')),
            ],
            options={
                'unique_together': {('song', 'show')},
            },
        ),
    ]
