# Generated by Django 3.1.7 on 2021-05-24 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_performance_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('source', models.CharField(choices=[('jury', 'Jury'), ('televote', 'Televote')], max_length=16)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.country')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.performance')),
            ],
            options={
                'unique_together': {('country', 'performance', 'source')},
            },
        ),
    ]
