# Generated by Django 3.1.7 on 2021-05-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='occurred',
            field=models.BooleanField(default=True),
        ),
    ]
